# Generated by Django 5.0.1 on 2024-06-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='photo',
            new_name='phone',
        ),
    ]
